### ISSUE TITLE
Rave + ipdapter

### ISSUE THREAD

**Issue by segalinc** [spacepxl/ComfyUI-RAVE#3]
If I was to use RAVE +animatediff with IP adapter would you recommend to connect ipadapter as model to the unsampler and ksamplerRAVE or after the animatediff?

**Comment by spacepxl** [comment]
I would recommend using IPAdapter for both RAVE and AnimateDiff. Not sure if there would be any benefit to applying it to the Unsampler, but in theory if you're using a >1 CFG in the Unsampler and using actual prompts instead of just empty conditioning, maybe it could act similarly to negative conditioning. In my experience there's usually not much reason to add real prompts for inversion instead of just adding a negative prompt to the ksampler.

**Comment by segalinc** [comment]
would you also recommend it when using sdxl models?

**Comment by spacepxl** [comment]
I haven't had much luck yet using RAVE with SDXL, I think it's because the multi-aspect-ratio training reduced the tiling effect compared to SD 1.5
